"""initial synchronized schema (DR v4 engine + DF potential + benchmarking)

Implements docs/DATA_MODEL.md. Raw SQL for fidelity to the legacy DR v4 dump,
TimescaleDB hypertables, arrays, and views.

Revision ID: 0001
Revises:
Create Date: 2026-07-15
"""
from alembic import op

revision = "0001"
down_revision = None
branch_labels = None
depends_on = None


SCHEMA_SQL = r"""
-- ── extensions ────────────────────────────────────────────────────────────
CREATE EXTENSION IF NOT EXISTS timescaledb;

-- ── reference / dimensions ────────────────────────────────────────────────
CREATE TABLE climate_zone (
    climate_zone_id   integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    climate_zone_description text NOT NULL UNIQUE,   -- '3C','2B', ...
    cec_cz            text
);

CREATE TABLE vintage (
    code text PRIMARY KEY                            -- '1980-2004','pre-1980','post-2004'
);

CREATE TABLE building_type_group (
    bldg_type_group_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bldg_type_group_description text NOT NULL UNIQUE,
    sector text                                      -- 'commercial' | 'residential'
);

CREATE TABLE building_types (
    bldg_type_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    description text,
    bldg_type_group_id integer REFERENCES building_type_group(bldg_type_group_id)
);

CREATE TABLE dr_programs (
    program_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    description text,
    code_description text
);

CREATE TABLE utilities (
    utility_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    description text
);

CREATE TABLE utility_program_links (
    utility_id integer NOT NULL REFERENCES utilities(utility_id),
    program_id integer NOT NULL REFERENCES dr_programs(program_id),
    PRIMARY KEY (utility_id, program_id)
);

CREATE TABLE location_descriptions (
    location_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    description text
);

-- ── DF strategy taxonomy (replaces legacy dr_strategies) ──────────────────
CREATE TABLE strategy_category (
    category_id integer PRIMARY KEY,
    code text NOT NULL UNIQUE,                        -- 'BE','HVAC','HVAC-P','LTG', ...
    name text NOT NULL,
    sector text,                                      -- 'commercial'|'residential'|'both'|...
    legacy_id integer,                                -- back-ref to legacy dr_strategies.strategy_id
    description text
);

CREATE TABLE df_strategy (
    strategy_id integer PRIMARY KEY,                  -- surrogate (keeps dr_strategy_links FK)
    strategy_code text NOT NULL UNIQUE,               -- 'HVAC-A1','BE-A1', ...
    name text NOT NULL,
    category_id integer NOT NULL REFERENCES strategy_category(category_id),
    sub_category text,
    description text,
    recommended_sequence text,
    response_speed text,
    flex_categories text[] NOT NULL DEFAULT '{}',     -- 'Efficiency','Shed','Shift', ...
    grid_services  text[] NOT NULL DEFAULT '{}',
    references_note text
);

CREATE TABLE df_strategy_level (
    strategy_id integer NOT NULL REFERENCES df_strategy(strategy_id),
    level text NOT NULL CHECK (level IN ('low','medium','high')),
    setting_value text,
    unit text,
    PRIMARY KEY (strategy_id, level)
);

-- ── users & access ────────────────────────────────────────────────────────
CREATE TABLE user_status (
    status_id integer PRIMARY KEY,
    status_description text,
    password_reset boolean
);

CREATE TABLE users (
    user_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name text,
    last_name text,
    email text NOT NULL UNIQUE,
    password text,                                    -- bcrypt hash
    status_id integer REFERENCES user_status(status_id),
    role text NOT NULL DEFAULT 'guest'
        CHECK (role IN ('admin','analyst','utility_pm','owner','guest')),
    created_date timestamptz DEFAULT now(),
    comments text
);

CREATE TABLE user_group_links (
    user_group_id integer NOT NULL,
    user_id integer NOT NULL REFERENCES users(user_id),
    PRIMARY KEY (user_group_id, user_id)
);

-- ── files / provenance ────────────────────────────────────────────────────
CREATE TABLE file_types (
    file_type_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    file_type_name text                               -- 'load','weather', ...
);

CREATE TABLE file_groups (
    file_group_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_group_id integer,
    group_name text NOT NULL,
    group_description text,
    created_time timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE import_files (
    file_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    file_group_id integer REFERENCES file_groups(file_group_id),
    file_type_id integer REFERENCES file_types(file_type_id),
    file_name text,
    file_description text,
    import_date timestamptz DEFAULT now()
);

-- ── sites & groups ────────────────────────────────────────────────────────
CREATE TABLE site_groups (
    site_group_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    site_group_name text NOT NULL,
    site_group_description text,
    comments text,
    file_group_id integer REFERENCES file_groups(file_group_id),
    hidden boolean DEFAULT false
);

CREATE TABLE sites (
    site_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    site_group_id integer REFERENCES site_groups(site_group_id),
    site_name text,
    site_description text,
    building_size_ft2 double precision,
    year_built integer,
    zip integer,
    climate_zone integer REFERENCES climate_zone(climate_zone_id),
    location_id integer REFERENCES location_descriptions(location_id),
    bldg_type_id integer REFERENCES building_types(bldg_type_id),
    bldg_sub_type_id integer,
    utility_id integer REFERENCES utilities(utility_id),
    strategy_id integer REFERENCES df_strategy(strategy_id),   -- legacy single-strategy col
    file_group_id integer REFERENCES file_groups(file_group_id),
    -- extended metadata: only fields consistently available across all data
    -- sources (batch3/batch4 retail + paper site summaries + future uploads)
    site_code text UNIQUE,
    sector text,
    vintage_code text REFERENCES vintage(code),
    year_renovated integer,
    city text,
    state text,
    longitude double precision,
    latitude double precision,
    hvac_type text,
    baseline_model text,
    data_source text,
    owner_user_id integer REFERENCES users(user_id)
);
CREATE INDEX idx_sites_climate ON sites(climate_zone);
CREATE INDEX idx_sites_bldg_type ON sites(bldg_type_id);
CREATE INDEX idx_sites_state ON sites(state);
CREATE INDEX idx_sites_data_source ON sites(data_source);

CREATE TABLE site_group_user_links (
    site_group_id integer NOT NULL REFERENCES site_groups(site_group_id),
    user_id integer NOT NULL REFERENCES users(user_id),
    PRIMARY KEY (site_group_id, user_id)
);

CREATE TABLE dr_strategy_links (
    strategy_id integer NOT NULL REFERENCES df_strategy(strategy_id),
    site_id integer NOT NULL REFERENCES sites(site_id),
    PRIMARY KEY (strategy_id, site_id)
);

CREATE TABLE holidays (
    holiday_date date PRIMARY KEY,
    description text
);

CREATE TABLE zip_to_climate_zone (
    zip_code text,
    climate_zone_id integer REFERENCES climate_zone(climate_zone_id),
    city text,
    location text
);
CREATE INDEX idx_zip_cz ON zip_to_climate_zone(zip_code);

-- ── interval time-series (TimescaleDB hypertables) ────────────────────────
CREATE TABLE interval_load (
    site_id integer NOT NULL REFERENCES sites(site_id),
    file_id integer REFERENCES import_files(file_id),
    ts timestamptz NOT NULL,
    kw double precision,
    wft2 double precision,
    PRIMARY KEY (site_id, ts)
);
SELECT create_hypertable('interval_load', 'ts',
       chunk_time_interval => INTERVAL '30 days', if_not_exists => TRUE);

CREATE TABLE interval_weather (
    station_id integer NOT NULL,
    file_id integer REFERENCES import_files(file_id),
    ts timestamptz NOT NULL,
    oat_f double precision,
    PRIMARY KEY (station_id, ts)
);
SELECT create_hypertable('interval_weather', 'ts',
       chunk_time_interval => INTERVAL '30 days', if_not_exists => TRUE);

-- compatibility views so ported baseline functions read kw_data/weather_data
CREATE VIEW kw_data      AS SELECT site_id    AS kw_id,      ts AS time_stamp, kw    AS value FROM interval_load;
CREATE VIEW weather_data AS SELECT station_id AS weather_id, ts AS time_stamp, oat_f AS value FROM interval_weather;

-- ── analysis engine (reused DR v4 core) ───────────────────────────────────
CREATE TABLE dr_analysis (
    analysis_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    analysis_name text NOT NULL,
    analysis_description text,
    site_id integer REFERENCES sites(site_id),
    program_id integer REFERENCES dr_programs(program_id),
    start_time time, end_time time,
    high_start_time time, high_end_time time,
    interpolate_data boolean DEFAULT false,
    interp_interval smallint,
    sensitivity_start_date date, sensitivity_end_date date,
    last_update timestamptz DEFAULT now(),
    load_file_id integer REFERENCES import_files(file_id),
    weather_file_id integer REFERENCES import_files(file_id)
);

CREATE TABLE dr_analysis_dates (
    analysis_id integer NOT NULL REFERENCES dr_analysis(analysis_id),
    dr_date date NOT NULL,
    PRIMARY KEY (analysis_id, dr_date)
);

CREATE TABLE dr_date_exclusions (
    analysis_id integer NOT NULL REFERENCES dr_analysis(analysis_id),
    dr_date date NOT NULL,
    PRIMARY KEY (analysis_id, dr_date)
);

CREATE TABLE dr_exclusions (
    analysis_id integer NOT NULL PRIMARY KEY REFERENCES dr_analysis(analysis_id),
    ex_weekends boolean DEFAULT true,
    ex_weekdays boolean DEFAULT false,
    ex_sun  boolean DEFAULT false, ex_mon boolean DEFAULT false,
    ex_tues boolean DEFAULT false, ex_wed boolean DEFAULT false,
    ex_thur boolean DEFAULT false, ex_fri boolean DEFAULT false,
    ex_sat  boolean DEFAULT false,
    ex_dr_days boolean DEFAULT true, ex_holidays boolean DEFAULT true
);

CREATE TABLE dr_analysis_file_links (
    file_id integer REFERENCES import_files(file_id),
    analysis_id integer NOT NULL REFERENCES dr_analysis(analysis_id),
    file_type_id integer NOT NULL REFERENCES file_types(file_type_id),
    PRIMARY KEY (analysis_id, file_type_id)
);

CREATE TABLE dr_analysis_noaa_links (
    station_id integer,
    analysis_id integer NOT NULL PRIMARY KEY REFERENCES dr_analysis(analysis_id)
);

CREATE TABLE baseline_types (
    baseline_type_id integer PRIMARY KEY,
    description text
);

CREATE TABLE baseline_adjustment (
    baseline_adjustment_id integer PRIMARY KEY,
    baseline_adjustment_description text NOT NULL
);

CREATE TABLE baselines (
    baseline_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    analysis_id integer REFERENCES dr_analysis(analysis_id),
    baseline_type_id integer REFERENCES baseline_types(baseline_type_id),
    param1 integer,                                   -- X (highest days) or num_days
    param2 integer,                                   -- Y (pool size)
    adj_start_time time, adj_end_time time,
    lower_cap_percentage double precision,
    upper_cap_percentage double precision,
    baseline_adjustment_id integer REFERENCES baseline_adjustment(baseline_adjustment_id)
);

CREATE TABLE analysis_results (
    analysis_result_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    analysis_id integer REFERENCES dr_analysis(analysis_id),
    analysis_update_time timestamptz
);

CREATE TABLE analysis_results_data (
    analysis_result_id integer REFERENCES analysis_results(analysis_result_id),
    baseline_id integer NOT NULL REFERENCES baselines(baseline_id),
    dr_date date NOT NULL,
    time_stamp timestamptz NOT NULL,
    load_value double precision,
    baseline_value double precision,
    temperature double precision,
    PRIMARY KEY (baseline_id, dr_date, time_stamp)
);

-- ── DF potential (simulation) ─────────────────────────────────────────────
CREATE TABLE sim_result (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bldg_type_id integer REFERENCES building_types(bldg_type_id),
    vintage_code text REFERENCES vintage(code),
    climate_zone_id integer REFERENCES climate_zone(climate_zone_id),
    strategy_id integer REFERENCES df_strategy(strategy_id),
    gta_level_f numeric, highest_gta_scenario text,     -- e.g. 'Precool-2F+GTA-4F'
    ddi_gta_only_wft2 numeric, ddi_precool_adj_wft2 numeric, delta_ddi_wft2 numeric,
    ddi_increase_pct numeric, kw_shed_per_10k_sf numeric, kw_shed_increase_per_10k numeric,
    pct_shed_of_baseline numeric, dii numeric,
    precool_kwh_change_pct numeric, net_kwh_increase_pct numeric, optmax_gta_f numeric
);
CREATE INDEX idx_sim_result_cohort ON sim_result(bldg_type_id, vintage_code, climate_zone_id);

-- DF potential estimator: piecewise-linear regressions of DR potential vs OAT
-- (breaks at 75/95 degF). Two strategy families share this table:
--   GTA temp reset (HVAC-A1)      — df-estimation *-Equations.csv (no CZ dimension)
--   RTU duty cycling (HVAC-P3)    — LBNL ADR Tool V2.1 CZ*CycleOnOff tables;
--     equations give full-hour cycling DR%; estimator scales by minutes_off/60.
CREATE TABLE potential_equation (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bldg_type_id integer REFERENCES building_types(bldg_type_id),
    strategy_id integer REFERENCES df_strategy(strategy_id),
    climate_zone_id integer REFERENCES climate_zone(climate_zone_id),  -- NULL for GTA set
    measure_id text,                     -- 'GTA-10-14-0-14-18-2-LTG-0' | 'SmallOfficeCZ03CycleYes1'
    precool_deg numeric,
    reset_deg numeric,
    compressor_only boolean,             -- duty cycling: compressor-only vs whole-RTU
    event_hour integer,                  -- 1..4 hours into the DR event
    output_unit text,                    -- 'pct' (DR potential %) | 'wft2' (shed W/ft2)
    oat_break_low numeric DEFAULT 75,
    oat_break_high numeric DEFAULT 95,
    seg1_alpha numeric, seg1_beta numeric,   -- OAT <= oat_break_low
    seg2_alpha numeric, seg2_beta numeric,   -- oat_break_low < OAT <= oat_break_high
    seg3_alpha numeric, seg3_beta numeric    -- OAT > oat_break_high
);
-- PG14-compatible uniqueness with NULLs treated as equal (NULLS NOT DISTINCT
-- needs PG15+): unique expression index over null-coalesced key columns.
CREATE UNIQUE INDEX uq_poteq_key ON potential_equation (
    coalesce(bldg_type_id, -1), coalesce(climate_zone_id, -1),
    coalesce(measure_id, ''), coalesce(precool_deg, -999), coalesce(reset_deg, -999),
    coalesce(compressor_only::text, '~'), coalesce(event_hour, -1), output_unit
);
CREATE INDEX idx_poteq_lookup ON potential_equation(bldg_type_id, output_unit, event_hour);

-- ── self-service uploads (Phase 2 provenance) ─────────────────────────────
CREATE TABLE upload_batch (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id integer REFERENCES users(user_id),
    kind text,                                        -- 'interval_load','events','site_meta'
    filename text,
    status text,                                      -- received|validated|loaded|failed
    row_count integer,
    error_log jsonb,
    created_at timestamptz DEFAULT now()
);

-- ── post-processed DR performance (Tier B) ────────────────────────────────
CREATE TABLE dr_event_performance (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    site_id integer REFERENCES sites(site_id),
    analysis_id integer REFERENCES dr_analysis(analysis_id),
    upload_batch_id bigint REFERENCES upload_batch(id),
    data_source text,
    event_seq integer,
    event_date date,
    shed_start timestamptz, shed_end timestamptz,
    program text,
    baseline_code text,
    baseline_type_id integer REFERENCES baseline_types(baseline_type_id),
    baseline_x integer, baseline_y integer,
    baseline_adjustment_id integer REFERENCES baseline_adjustment(baseline_adjustment_id),
    peak_oat_f numeric, event_avg_oat_f numeric, max_oat_f numeric,
    kw_max numeric, kw_avg numeric, kw_min numeric,
    peak_demand_intensity_wft2 numeric, shed_avg_wft2 numeric,
    wft2_max numeric, wft2_avg numeric, wft2_min numeric,
    wbp_pct_max numeric, wbp_pct_avg numeric, wbp_pct_min numeric,
    source_citation text,
    UNIQUE (site_id, event_date, shed_start, baseline_code)
);
CREATE INDEX idx_dep_site ON dr_event_performance(site_id);
CREATE INDEX idx_dep_date ON dr_event_performance(event_date);
CREATE INDEX idx_dep_source ON dr_event_performance(data_source);

-- ── benchmarking cohorts ──────────────────────────────────────────────────
-- Regular view for Phase 0; promote to MATERIALIZED VIEW in Phase 1c when data
-- volume warrants (docs/DATA_MODEL.md §6).
CREATE VIEW benchmark_cohort AS
SELECT
    s.bldg_type_id,
    s.vintage_code,
    s.climate_zone AS climate_zone_id,
    CASE WHEN s.building_size_ft2 < 50000  THEN 'small'
         WHEN s.building_size_ft2 < 200000 THEN 'medium'
         ELSE 'large' END AS size_bucket,
    count(*) AS n,
    avg(p.shed_avg_wft2) AS shed_wft2_mean,
    percentile_cont(0.25) WITHIN GROUP (ORDER BY p.shed_avg_wft2) AS shed_wft2_p25,
    percentile_cont(0.50) WITHIN GROUP (ORDER BY p.shed_avg_wft2) AS shed_wft2_median,
    percentile_cont(0.75) WITHIN GROUP (ORDER BY p.shed_avg_wft2) AS shed_wft2_p75,
    percentile_cont(0.90) WITHIN GROUP (ORDER BY p.shed_avg_wft2) AS shed_wft2_p90,
    avg(p.peak_demand_intensity_wft2) AS pdi_wft2_mean,
    avg(p.wbp_pct_avg) AS wbp_pct_mean
FROM dr_event_performance p
JOIN sites s ON s.site_id = p.site_id
GROUP BY s.bldg_type_id, s.vintage_code, s.climate_zone, 4;
"""


DROP_SQL = r"""
DROP VIEW IF EXISTS benchmark_cohort;
DROP VIEW IF EXISTS kw_data;
DROP VIEW IF EXISTS weather_data;
DROP TABLE IF EXISTS dr_event_performance CASCADE;
DROP TABLE IF EXISTS upload_batch CASCADE;
DROP TABLE IF EXISTS potential_equation CASCADE;
DROP TABLE IF EXISTS sim_result CASCADE;
DROP TABLE IF EXISTS analysis_results_data CASCADE;
DROP TABLE IF EXISTS analysis_results CASCADE;
DROP TABLE IF EXISTS baselines CASCADE;
DROP TABLE IF EXISTS baseline_adjustment CASCADE;
DROP TABLE IF EXISTS baseline_types CASCADE;
DROP TABLE IF EXISTS dr_analysis_noaa_links CASCADE;
DROP TABLE IF EXISTS dr_analysis_file_links CASCADE;
DROP TABLE IF EXISTS dr_exclusions CASCADE;
DROP TABLE IF EXISTS dr_date_exclusions CASCADE;
DROP TABLE IF EXISTS dr_analysis_dates CASCADE;
DROP TABLE IF EXISTS dr_analysis CASCADE;
DROP TABLE IF EXISTS interval_weather CASCADE;
DROP TABLE IF EXISTS interval_load CASCADE;
DROP TABLE IF EXISTS zip_to_climate_zone CASCADE;
DROP TABLE IF EXISTS holidays CASCADE;
DROP TABLE IF EXISTS dr_strategy_links CASCADE;
DROP TABLE IF EXISTS site_group_user_links CASCADE;
DROP TABLE IF EXISTS sites CASCADE;
DROP TABLE IF EXISTS site_groups CASCADE;
DROP TABLE IF EXISTS import_files CASCADE;
DROP TABLE IF EXISTS file_groups CASCADE;
DROP TABLE IF EXISTS file_types CASCADE;
DROP TABLE IF EXISTS user_group_links CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS user_status CASCADE;
DROP TABLE IF EXISTS df_strategy_level CASCADE;
DROP TABLE IF EXISTS df_strategy CASCADE;
DROP TABLE IF EXISTS strategy_category CASCADE;
DROP TABLE IF EXISTS location_descriptions CASCADE;
DROP TABLE IF EXISTS utility_program_links CASCADE;
DROP TABLE IF EXISTS utilities CASCADE;
DROP TABLE IF EXISTS dr_programs CASCADE;
DROP TABLE IF EXISTS building_types CASCADE;
DROP TABLE IF EXISTS building_type_group CASCADE;
DROP TABLE IF EXISTS vintage CASCADE;
DROP TABLE IF EXISTS climate_zone CASCADE;
"""


def upgrade() -> None:
    op.execute(SCHEMA_SQL)


def downgrade() -> None:
    op.execute(DROP_SQL)
